//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
* Ben Goldberg's 2 stage code framwork
*
*	Use:
*	-	Automatic switching between autonomous and teleop modes
*
*	Directions:
*
*	- Put autonomous code in the auton function
*	-	Put human remote control code in the teleop function
* - Start Button must be plugged into digital port 1
*	-	Digital port 1 must be configured as a touch sensor in Motor and Sensor Setup
*	-	The file "twoStage.h" must be in the same folder as this one
*
*	Use:
*	-	Press the start button to begin auton
*	-	Then the code in the auton function will run continuously for 30 seconds
*	-	Once auton in complete press the 8L button on the controller to begin teleop
*	-	Then the code in the teleop function will run continuously for 2 minuets
*
*	Errors:
*
*	-	If you get the error "Couldn't open '#include' file 'twoStage.h'"
*		then twoStage.h is not is the right place
*/

void auton() {
	//Put autonomous code here

	/*
	*	Example Auton Code:
	*	motor[port1] = 50;
	*	motor[port10] = 50;
	*/
}

void postAuton() {
	/*
	* Stop all of you motors here
	*	Example:
	*	motor[port1] = 0;
	*	motor[port10] = 0;
	*/
}

void teleop() {
	//Put teleop code here

	/*
	*	Example Teleop Code:
	*	motor[port1] = vexRT[Ch3];
	*	motor[port10] = vexRT[Ch2];
	*/
}

void postTeleop() {
	/*
	* Stop all of you motors here
	*	Example:
	*	motor[port1] = 0;
	*	motor[port10] = 0;
	*/
}


//Do not edit code bellow this point!
#include "twoStage.h"
task main() {
	twoStage();
}
